# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_auto_20170317_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trips/images', verbose_name='Imagem'),
        ),
    ]
