# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_auto_20170317_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='slug',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
